/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReferralLink = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'targetUrl' : IDL.Text,
  'clickCount' : IDL.Nat,
  'thumbnailPath' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReferralLinks' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
  'getReferralLinkById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ReferralLink)],
      ['query'],
    ),
  'redirectAndTrackClick' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReferralLink = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'targetUrl' : IDL.Text,
    'clickCount' : IDL.Nat,
    'thumbnailPath' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReferralLinks' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
    'getReferralLinkById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReferralLink)],
        ['query'],
      ),
    'redirectAndTrackClick' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };